# Generated by Django 3.1.1 on 2021-10-04 09:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=200)),
                ('album_artist', models.CharField(max_length=200)),
                ('number_of_tracks', models.PositiveIntegerField()),
                ('album_image', models.ImageField(blank=True, null=True, upload_to='uploads/albums', verbose_name='Album Image')),
                ('album_audio', models.FileField(blank=True, null=True, upload_to='upload')),
                ('slug', models.SlugField(max_length=200)),
                ('approve', models.BooleanField(default=False)),
                ('time_added', models.DateTimeField(default=datetime.datetime(2021, 10, 4, 10, 20, 5, 79653), verbose_name='date added')),
                ('album_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Album')),
            ],
            options={
                'verbose_name_plural': 'Album',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_member_name', models.CharField(max_length=200)),
                ('team_role', models.CharField(max_length=200)),
                ('team_image', models.FileField(blank=True, null=True, upload_to='media/upload')),
                ('profile', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=200)),
                ('track_artist', models.CharField(max_length=200)),
                ('track_image', models.ImageField(blank=True, null=True, upload_to='uploads/tracks', verbose_name='Track Image')),
                ('track_audio', models.FileField(blank=True, null=True, upload_to='upload')),
                ('track_genre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('approve', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Track',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=200)),
                ('album_of_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_album', to='frontend.album')),
                ('genre_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Genre')),
                ('track_of_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_track', to='frontend.track')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_of_album', to='frontend.album')),
                ('track_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_of_track', to='frontend.track')),
            ],
        ),
    ]
