# Generated by Django 3.1.1 on 2021-10-04 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='album_of_genre',
        ),
        migrations.AddField(
            model_name='album',
            name='album_genres',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 10, 22, 51, 775820), verbose_name='date added'),
        ),
    ]
