# Generated by Django 3.1.1 on 2021-09-29 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 17, 27, 31, 182179), verbose_name='date added'),
        ),
    ]
