# Generated by Django 3.1.1 on 2021-10-04 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20211004_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 15, 20, 59, 159183), verbose_name='date added'),
        ),
    ]
