# Generated by Django 3.1.1 on 2021-10-04 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20211004_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_member_name',
        ),
        migrations.AlterField(
            model_name='album',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 10, 26, 7, 875174), verbose_name='date added'),
        ),
    ]
