# Generated by Django 3.1.1 on 2021-10-05 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20211004_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 11, 31, 21, 249856), verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='album',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 11, 31, 21, 248850), verbose_name='date added'),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
