# Generated by Django 3.1.1 on 2021-10-04 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20211004_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='track_artist',
        ),
        migrations.AlterField(
            model_name='album',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 10, 29, 38, 111386), verbose_name='date added'),
        ),
    ]
