# Generated by Django 3.1.1 on 2021-10-04 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20211004_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_artists',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 10, 30, 49, 662843), verbose_name='date added'),
        ),
    ]
