# Generated by Django 3.1.1 on 2021-10-04 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20211004_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 11, 54, 3, 271833), verbose_name='date added'),
        ),
    ]
