# Generated by Django 3.1.1 on 2021-10-05 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20211005_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 14, 42, 47, 944024), verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='track',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 14, 42, 47, 945023), verbose_name='date added'),
        ),
    ]
