# Generated by Django 3.1.1 on 2021-10-06 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_auto_20211006_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 12, 48, 55, 734864), verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='track',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 12, 48, 55, 735863), verbose_name='date added'),
        ),
    ]
